// Style imports
import '@mantine/core/styles.css'
import '@mantine/dates/styles.css'
import '@mantine/notifications/styles.css'
import '@mantine/carousel/styles.css'
import '@mantine/dropzone/styles.css'

export type ColorScheme = 'light' | 'dark'

// Re-export all Mantine components and types
export type {
  AppShellProps,
  AspectRatioProps,
  CenterProps,
  ContainerProps,
  FlexProps,
  GridProps,
  GroupProps,
  SimpleGridProps,
  SpaceProps,
  StackProps,
  CheckboxProps,
  CheckboxGroupProps,
  ChipProps,
  ChipGroupProps,
  ColorInputProps,
  ColorPickerProps,
  FieldsetProps,
  FileInputProps,
  InputProps,
  InputWrapperProps,
  InputErrorProps,
  InputLabelProps,
  InputPlaceholderProps,
  InputBaseProps,
  JsonInputProps,
  NativeSelectProps,
  PasswordInputProps,
  PinInputProps,
  RadioProps,
  RadioGroupProps,
  RadioCardProps,
  RatingProps,
  SegmentedControlProps,
  SegmentedControlItem,
  SliderProps,
  RangeSliderProps,
  TextareaProps,
  AutocompleteProps,
  ComboboxProps,
  ComboboxItem,
  ComboboxData,
  ButtonProps,
  PillProps,
  PillsInputProps,
  OptionsFilter,
  TagsInputProps,
  ActionIconProps,
  CloseButtonProps,
  CopyButtonProps,
  FileButtonProps,
  UnstyledButtonProps,
  AnchorProps,
  BreadcrumbsProps,
  BurgerProps,
  NavLinkProps,
  PaginationProps,
  StepperProps,
  TabsProps,
  TreeProps,
  AlertProps,
  LoaderProps,
  NotificationProps,
  ProgressProps,
  RingProgressProps,
  SemiCircleProgressProps,
  SkeletonProps,
  AffixProps,
  DialogProps,
  DrawerProps,
  FloatingIndicatorProps,
  HoverCardProps,
  LoadingOverlayProps,
  MenuProps,
  ModalProps,
  OverlayProps,
  PopoverProps,
  TooltipProps,
  AccordionProps,
  AvatarProps,
  BackgroundImageProps,
  BadgeProps,
  CardProps,
  CardSectionProps,
  ColorSwatchProps,
  ImageProps,
  IndicatorProps,
  KbdProps,
  NumberFormatterProps,
  SpoilerProps,
  ThemeIconProps,
  TimelineProps,
  BlockquoteProps,
  CodeProps,
  HighlightProps,
  ListProps,
  MarkProps,
  TableProps,
  TextProps,
  SwitchProps,
  TitleProps,
  TypographyStylesProviderProps,
  BoxProps,
  BoxComponentProps,
  CollapseProps,
  DividerProps,
  FocusTrapProps,
  PaperProps,
  PortalProps,
  ScrollAreaProps,
  TransitionProps,
  VisuallyHiddenProps,
  ColorSchemeScriptProps,
  MantineSize,
  ElementProps,
  OptionsData,
  TableOfContentsProps
} from '@mantine/core'

export {
  AppShell,
  AspectRatio,
  Center,
  Container,
  Flex,
  Grid,
  Group,
  SimpleGrid,
  Space,
  Stack,
  AngleSlider,
  Checkbox,
  Chip,
  ColorInput,
  ColorPicker,
  CopyButton,
  Fieldset,
  HueSlider,
  AlphaSlider,
  FileInput,
  Input,
  InputBase,
  JsonInput,
  NativeSelect,
  PasswordInput,
  PinInput,
  Radio,
  RadioGroup,
  RadioCard,
  Rating,
  SegmentedControl,
  Slider,
  RangeSlider,
  Textarea,
  Text,
  Autocomplete,
  Combobox,
  Pill,
  PillsInput,
  TagsInput,
  ActionIcon,
  CloseButton,
  FileButton,
  UnstyledButton,
  Anchor,
  Breadcrumbs,
  Burger,
  NavLink,
  Pagination,
  Stepper,
  TableOfContents,
  Tabs,
  Tree,
  Alert,
  Loader,
  Notification,
  Progress,
  RingProgress,
  SemiCircleProgress,
  Skeleton,
  Affix,
  Dialog,
  Drawer,
  FloatingIndicator,
  HoverCard,
  LoadingOverlay,
  Menu,
  Modal,
  Overlay,
  Popover,
  Tooltip,
  Accordion,
  Avatar,
  BackgroundImage,
  Badge,
  Card,
  ColorSwatch,
  Image,
  Indicator,
  Kbd,
  NumberFormatter,
  Spoiler,
  ThemeIcon,
  Timeline,
  Blockquote,
  Code,
  Highlight,
  List,
  Mark,
  Table,
  Text as MantineText,
  Title,
  TypographyStylesProvider,
  Box,
  Collapse,
  Divider,
  FocusTrap,
  Paper,
  Portal,
  ScrollArea,
  Transition,
  VisuallyHidden,
  ColorSchemeScript,
  useInputProps,
  useMantineTheme,
  useCombobox,
  useComputedColorScheme,
  defaultOptionsFilter,
  getOptionsLockup,
  getParsedComboboxData,
  isOptionsGroup,
  useProps
} from '@mantine/core'

// Re-export @mantine/dropzone
export {
  Dropzone,
  MIME_TYPES,
  MS_EXCEL_MIME_TYPE,
  MS_POWERPOINT_MIME_TYPE,
  MS_WORD_MIME_TYPE,
  EXE_MIME_TYPE,
  PDF_MIME_TYPE,
  IMAGE_MIME_TYPE
} from '@mantine/dropzone'
export type {
  DropzoneAcceptProps,
  DropzoneFullScreenProps,
  DropzoneFullScreenStylesNames,
  DropzoneIdleProps,
  DropzoneProps,
  DropzoneRejectProps,
  DropzoneStylesNames
} from '@mantine/dropzone'

// Re-export @mantine/carousel
export { Carousel, useAnimationOffsetEffect } from '@mantine/carousel'
export type { CarouselProps, CarouselStylesNames, Embla } from '@mantine/carousel'

// Re-export @mantine/modals
export {
  ModalsProvider,
  useModals,
  openModal,
  openConfirmModal,
  openContextModal,
  closeModal,
  closeAllModals
} from '@mantine/modals'
export type { ModalsProviderProps, ContextModalProps } from '@mantine/modals'

// Re-export @mantine/dates
export { DatePicker, DatePickerInput, Calendar, Month, TimeInput } from '@mantine/dates'
export type {
  CalendarProps,
  CalendarBaseProps,
  DatePickerType,
  DatePickerProps,
  DatePickerInputProps,
  DatePickerStylesNames,
  MonthProps,
  TimeInputProps,
  MonthSettings
} from '@mantine/dates'

// Your custom primitives
export { Button } from './Button/index.js'
export { Typography, type TypographyProps } from './Typography/index.js'

export { Select, type SelectProps } from './Select/index.js'
export { MultiSelect, type MultiSelectProps } from './Select/index.js'

export { Switch } from './Switch/index.js'

export { TextInput, type TextInputProps } from './TextInput/index.js'

export { NumberInput, type NumberInputProps } from './NumberInput/index.js'

export * from './notifier/index.js'

// Hooks — re-export from sibling folder
export { useColorScheme } from '../hooks/index.js'

// Business components — root convenience exports
