/**
 * Semantic Background Tokens — Light Mode
 *
 * Sourced from @atlaskit/tokens atlassian-light.json
 */

export const backgroundColors = {
  /* ── Accent: Lime ── */
  'color.background.accent.lime.subtlest': '#F7FEE7',
  'color.background.accent.lime.subtlest.hovered': '#ECFCCB',
  'color.background.accent.lime.subtlest.pressed': '#D9F99D',
  'color.background.accent.lime.subtler': '#ECFCCB',
  'color.background.accent.lime.subtler.hovered': '#D9F99D',
  'color.background.accent.lime.subtler.pressed': '#BEF264',
  'color.background.accent.lime.subtle': '#BEF264',
  'color.background.accent.lime.subtle.hovered': '#A3E635',
  'color.background.accent.lime.subtle.pressed': '#84CC16',
  'color.background.accent.lime.bolder': '#65A30D',
  'color.background.accent.lime.bolder.hovered': '#4D7C0F',
  'color.background.accent.lime.bolder.pressed': '#3F6212',

  /* ── Accent: Red ── */
  'color.background.accent.red.subtlest': '#FEF2F2',
  'color.background.accent.red.subtlest.hovered': '#FEE2E2',
  'color.background.accent.red.subtlest.pressed': '#FECACA',
  'color.background.accent.red.subtler': '#FEE2E2',
  'color.background.accent.red.subtler.hovered': '#FECACA',
  'color.background.accent.red.subtler.pressed': '#FCA5A5',
  'color.background.accent.red.subtle': '#FCA5A5',
  'color.background.accent.red.subtle.hovered': '#F87171',
  'color.background.accent.red.subtle.pressed': '#EF4444',
  'color.background.accent.red.bolder': '#DC2626',
  'color.background.accent.red.bolder.hovered': '#B91C1C',
  'color.background.accent.red.bolder.pressed': '#991B1B',

  /* ── Accent: Orange ── */
  'color.background.accent.orange.subtlest': '#FFF7ED',
  'color.background.accent.orange.subtlest.hovered': '#FFEDD5',
  'color.background.accent.orange.subtlest.pressed': '#FED7AA',
  'color.background.accent.orange.subtler': '#FFEDD5',
  'color.background.accent.orange.subtler.hovered': '#FED7AA',
  'color.background.accent.orange.subtler.pressed': '#FDBA74',
  'color.background.accent.orange.subtle': '#FDBA74',
  'color.background.accent.orange.subtle.hovered': '#FB923C',
  'color.background.accent.orange.subtle.pressed': '#F97316',
  'color.background.accent.orange.bolder': '#EA580C',
  'color.background.accent.orange.bolder.hovered': '#C2410C',
  'color.background.accent.orange.bolder.pressed': '#9A3412',

  /* ── Accent: Yellow ── */
  'color.background.accent.yellow.subtlest': '#FEFCE8',
  'color.background.accent.yellow.subtlest.hovered': '#FEF9C3',
  'color.background.accent.yellow.subtlest.pressed': '#FEF08A',
  'color.background.accent.yellow.subtler': '#FEF9C3',
  'color.background.accent.yellow.subtler.hovered': '#FEF08A',
  'color.background.accent.yellow.subtler.pressed': '#FDE047',
  'color.background.accent.yellow.subtle': '#FDE047',
  'color.background.accent.yellow.subtle.hovered': '#FACC15',
  'color.background.accent.yellow.subtle.pressed': '#EAB308',
  'color.background.accent.yellow.bolder': '#CA8A04',
  'color.background.accent.yellow.bolder.hovered': '#A16207',
  'color.background.accent.yellow.bolder.pressed': '#854D0E',

  /* ── Accent: Green ── */
  'color.background.accent.green.subtlest': '#F0FDF4',
  'color.background.accent.green.subtlest.hovered': '#DCFCE7',
  'color.background.accent.green.subtlest.pressed': '#BBF7D0',
  'color.background.accent.green.subtler': '#DCFCE7',
  'color.background.accent.green.subtler.hovered': '#BBF7D0',
  'color.background.accent.green.subtler.pressed': '#86EFAC',
  'color.background.accent.green.subtle': '#86EFAC',
  'color.background.accent.green.subtle.hovered': '#4ADE80',
  'color.background.accent.green.subtle.pressed': '#22C55E',
  'color.background.accent.green.bolder': '#16A34A',
  'color.background.accent.green.bolder.hovered': '#15803D',
  'color.background.accent.green.bolder.pressed': '#14532D',

  /* ── Accent: Teal ── */
  'color.background.accent.teal.subtlest': '#F0FDFA',
  'color.background.accent.teal.subtlest.hovered': '#CCFBF1',
  'color.background.accent.teal.subtlest.pressed': '#99F6E4',
  'color.background.accent.teal.subtler': '#CCFBF1',
  'color.background.accent.teal.subtler.hovered': '#99F6E4',
  'color.background.accent.teal.subtler.pressed': '#5EEAD4',
  'color.background.accent.teal.subtle': '#5EEAD4',
  'color.background.accent.teal.subtle.hovered': '#2DD4BF',
  'color.background.accent.teal.subtle.pressed': '#14B8A6',
  'color.background.accent.teal.bolder': '#0D9488',
  'color.background.accent.teal.bolder.hovered': '#0F766E',
  'color.background.accent.teal.bolder.pressed': '#134E4A',

  /* ── Accent: Blue ── */
  'color.background.accent.blue.subtlest': '#F0F9FF',
  'color.background.accent.blue.subtlest.hovered': '#E0F2FE',
  'color.background.accent.blue.subtlest.pressed': '#BAE6FD',
  'color.background.accent.blue.subtler': '#E0F2FE',
  'color.background.accent.blue.subtler.hovered': '#BAE6FD',
  'color.background.accent.blue.subtler.pressed': '#7DD3FC',
  'color.background.accent.blue.subtle': '#7DD3FC',
  'color.background.accent.blue.subtle.hovered': '#38BDF8',
  'color.background.accent.blue.subtle.pressed': '#0EA5E9',
  'color.background.accent.blue.bolder': '#0284C7',
  'color.background.accent.blue.bolder.hovered': '#0369A1',
  'color.background.accent.blue.bolder.pressed': '#0C4A6E',

  /* ── Accent: Purple ── */
  'color.background.accent.purple.subtlest': '#F5F3FF',
  'color.background.accent.purple.subtlest.hovered': '#EDE9FE',
  'color.background.accent.purple.subtlest.pressed': '#DDD6FE',
  'color.background.accent.purple.subtler': '#EDE9FE',
  'color.background.accent.purple.subtler.hovered': '#DDD6FE',
  'color.background.accent.purple.subtler.pressed': '#C4B5FD',
  'color.background.accent.purple.subtle': '#C4B5FD',
  'color.background.accent.purple.subtle.hovered': '#A78BFA',
  'color.background.accent.purple.subtle.pressed': '#8B5CF6',
  'color.background.accent.purple.bolder': '#7C3AED',
  'color.background.accent.purple.bolder.hovered': '#6D28D9',
  'color.background.accent.purple.bolder.pressed': '#4C1D95',

  /* ── Accent: Magenta ── */
  'color.background.accent.magenta.subtlest': '#FDF2F8',
  'color.background.accent.magenta.subtlest.hovered': '#FCE7F3',
  'color.background.accent.magenta.subtlest.pressed': '#FBCFE8',
  'color.background.accent.magenta.subtler': '#FCE7F3',
  'color.background.accent.magenta.subtler.hovered': '#FBCFE8',
  'color.background.accent.magenta.subtler.pressed': '#F9A8D4',
  'color.background.accent.magenta.subtle': '#F9A8D4',
  'color.background.accent.magenta.subtle.hovered': '#F472B6',
  'color.background.accent.magenta.subtle.pressed': '#EC4899',
  'color.background.accent.magenta.bolder': '#DB2777',
  'color.background.accent.magenta.bolder.hovered': '#BE185D',
  'color.background.accent.magenta.bolder.pressed': '#831843',

  /* ── Accent: Gray ── */
  'color.background.accent.gray.subtlest': '#FAFAFA',
  'color.background.accent.gray.subtlest.hovered': '#F4F4F5',
  'color.background.accent.gray.subtlest.pressed': '#E4E4E7',
  'color.background.accent.gray.subtler': '#F4F4F5',
  'color.background.accent.gray.subtler.hovered': '#E4E4E7',
  'color.background.accent.gray.subtler.pressed': '#D4D4D8',
  'color.background.accent.gray.subtle': '#D4D4D8',
  'color.background.accent.gray.subtle.hovered': '#A1A1AA',
  'color.background.accent.gray.subtle.pressed': '#71717A',
  'color.background.accent.gray.bolder': '#52525B',
  'color.background.accent.gray.bolder.hovered': '#3F3F46',
  'color.background.accent.gray.bolder.pressed': '#27272A',

  /* ── Neutral / Base ── */
  'color.background.disabled': '#F4F4F5',
  'color.background.input': '#FFFFFF',
  'color.background.input.hovered': '#FAFAFA',
  'color.background.input.pressed': '#F4F4F5',
  'color.background.inverse.subtle': 'rgba(0, 0, 0, 0.06)',
  'color.background.inverse.subtle.hovered': 'rgba(0, 0, 0, 0.1)',
  'color.background.inverse.subtle.pressed': 'rgba(0, 0, 0, 0.14)',

  'color.background.neutral': '#F4F4F5',
  'color.background.neutral.hovered': '#E4E4E7',
  'color.background.neutral.pressed': '#D4D4D8',
  'color.background.neutral.subtle': '#00000000',
  'color.background.neutral.subtle.hovered': '#FAFAFA',
  'color.background.neutral.subtle.pressed': '#F4F4F5',
  'color.background.neutral.bold': '#18181B',
  'color.background.neutral.bold.hovered': '#09090B',
  'color.background.neutral.bold.pressed': '#09090B',

  /* ── Selected ── */
  'color.background.selected': '#F5F5F5',
  'color.background.selected.hovered': '#E5E5E5',
  'color.background.selected.pressed': '#D4D4D4',
  'color.background.selected.bold': '#2E2E2E',
  'color.background.selected.bold.hovered': '#1A1A1A',
  'color.background.selected.bold.pressed': '#1A1A1A',

  /* ── Brand ── */
  'color.background.brand.subtlest': '#F5F5F5',
  'color.background.brand.subtlest.hovered': '#E5E5E5',
  'color.background.brand.subtlest.pressed': '#D4D4D4',
  'color.background.brand.bold': '#2E2E2E',
  'color.background.brand.bold.hovered': '#1A1A1A',
  'color.background.brand.bold.pressed': '#1A1A1A',
  'color.background.brand.boldest': '#1A1A1A',
  'color.background.brand.boldest.hovered': '#09090B',
  'color.background.brand.boldest.pressed': '#09090B',

  /* ── Danger ── */
  'color.background.danger': '#FEF2F2',
  'color.background.danger.hovered': '#FEE2E2',
  'color.background.danger.pressed': '#FECACA',
  'color.background.danger.subtler': '#FEE2E2',
  'color.background.danger.subtler.hovered': '#FECACA',
  'color.background.danger.subtler.pressed': '#FCA5A5',
  'color.background.danger.subtle': '#FEE2E2',
  'color.background.danger.bold': '#DC2626',
  'color.background.danger.bold.hovered': '#B91C1C',
  'color.background.danger.bold.pressed': '#991B1B',

  /* ── Warning ── */
  'color.background.warning': '#FFFBEB',
  'color.background.warning.hovered': '#FEF3C7',
  'color.background.warning.pressed': '#FDE68A',
  'color.background.warning.subtler': '#FEF3C7',
  'color.background.warning.subtler.hovered': '#FDE68A',
  'color.background.warning.subtler.pressed': '#FCD34D',
  'color.background.warning.subtle': '#FEF3C7',
  'color.background.warning.bold': '#F59E0B',
  'color.background.warning.bold.hovered': '#D97706',
  'color.background.warning.bold.pressed': '#B45309',

  /* ── Success ── */
  'color.background.success': '#F0FDF4',
  'color.background.success.hovered': '#DCFCE7',
  'color.background.success.pressed': '#BBF7D0',
  'color.background.success.subtler': '#DCFCE7',
  'color.background.success.subtler.hovered': '#BBF7D0',
  'color.background.success.subtler.pressed': '#86EFAC',
  'color.background.success.subtle': '#DCFCE7',
  'color.background.success.bold': '#16A34A',
  'color.background.success.bold.hovered': '#15803D',
  'color.background.success.bold.pressed': '#166534',

  /* ── Discovery ── */
  'color.background.discovery': '#F5F3FF',
  'color.background.discovery.hovered': '#EDE9FE',
  'color.background.discovery.pressed': '#DDD6FE',
  'color.background.discovery.subtler': '#EDE9FE',
  'color.background.discovery.subtler.hovered': '#DDD6FE',
  'color.background.discovery.subtler.pressed': '#C4B5FD',
  'color.background.discovery.subtle': '#DDD6FE',
  'color.background.discovery.bold': '#8B5CF6',
  'color.background.discovery.bold.hovered': '#7C3AED',
  'color.background.discovery.bold.pressed': '#6D28D9',

  /* ── Information ── */
  'color.background.information': '#EEF2FF',
  'color.background.information.hovered': '#E0E7FF',
  'color.background.information.pressed': '#C7D2FE',
  'color.background.information.subtler': '#E0E7FF',
  'color.background.information.subtler.hovered': '#C7D2FE',
  'color.background.information.subtler.pressed': '#A5B4FC',
  'color.background.information.subtle': '#C7D2FE',
  'color.background.information.bold': '#4F46E5',
  'color.background.information.bold.hovered': '#4338CA',
  'color.background.information.bold.pressed': '#3730A3'
} as const

export type BackgroundColorToken = keyof typeof backgroundColors
