/**
 * Semantic Background Tokens — Dark Mode
 *
 * Sourced from @atlaskit/tokens atlassian-dark.json
 */

export const backgroundColorsDark = {
  /* ── Accent: Lime ── */
  'color.background.accent.lime.subtlest': '#1A2E05',
  'color.background.accent.lime.subtlest.hovered': '#365314',
  'color.background.accent.lime.subtlest.pressed': '#3F6212',
  'color.background.accent.lime.subtler': '#365314',
  'color.background.accent.lime.subtler.hovered': '#3F6212',
  'color.background.accent.lime.subtler.pressed': '#4D7C0F',
  'color.background.accent.lime.subtle': '#4D7C0F',
  'color.background.accent.lime.subtle.hovered': '#65A30D',
  'color.background.accent.lime.subtle.pressed': '#84CC16',
  'color.background.accent.lime.bolder': '#A3E635',
  'color.background.accent.lime.bolder.hovered': '#BEF264',
  'color.background.accent.lime.bolder.pressed': '#D9F99D',

  /* ── Accent: Red ── */
  'color.background.accent.red.subtlest': '#450A0A',
  'color.background.accent.red.subtlest.hovered': '#7F1D1D',
  'color.background.accent.red.subtlest.pressed': '#991B1B',
  'color.background.accent.red.subtler': '#7F1D1D',
  'color.background.accent.red.subtler.hovered': '#991B1B',
  'color.background.accent.red.subtler.pressed': '#B91C1C',
  'color.background.accent.red.subtle': '#B91C1C',
  'color.background.accent.red.subtle.hovered': '#DC2626',
  'color.background.accent.red.subtle.pressed': '#EF4444',
  'color.background.accent.red.bolder': '#F87171',
  'color.background.accent.red.bolder.hovered': '#FCA5A5',
  'color.background.accent.red.bolder.pressed': '#FECACA',

  /* ── Accent: Orange ── */
  'color.background.accent.orange.subtlest': '#431407',
  'color.background.accent.orange.subtlest.hovered': '#7C2D12',
  'color.background.accent.orange.subtlest.pressed': '#9A3412',
  'color.background.accent.orange.subtler': '#7C2D12',
  'color.background.accent.orange.subtler.hovered': '#9A3412',
  'color.background.accent.orange.subtler.pressed': '#C2410C',
  'color.background.accent.orange.subtle': '#C2410C',
  'color.background.accent.orange.subtle.hovered': '#EA580C',
  'color.background.accent.orange.subtle.pressed': '#F97316',
  'color.background.accent.orange.bolder': '#FB923C',
  'color.background.accent.orange.bolder.hovered': '#FDBA74',
  'color.background.accent.orange.bolder.pressed': '#FED7AA',

  /* ── Accent: Yellow ── */
  'color.background.accent.yellow.subtlest': '#422006',
  'color.background.accent.yellow.subtlest.hovered': '#713F12',
  'color.background.accent.yellow.subtlest.pressed': '#854D0E',
  'color.background.accent.yellow.subtler': '#713F12',
  'color.background.accent.yellow.subtler.hovered': '#854D0E',
  'color.background.accent.yellow.subtler.pressed': '#A16207',
  'color.background.accent.yellow.subtle': '#A16207',
  'color.background.accent.yellow.subtle.hovered': '#CA8A04',
  'color.background.accent.yellow.subtle.pressed': '#EAB308',
  'color.background.accent.yellow.bolder': '#FACC15',
  'color.background.accent.yellow.bolder.hovered': '#FDE047',
  'color.background.accent.yellow.bolder.pressed': '#FEF08A',

  /* ── Accent: Green ── */
  'color.background.accent.green.subtlest': '#052E16',
  'color.background.accent.green.subtlest.hovered': '#14532D',
  'color.background.accent.green.subtlest.pressed': '#166534',
  'color.background.accent.green.subtler': '#14532D',
  'color.background.accent.green.subtler.hovered': '#166534',
  'color.background.accent.green.subtler.pressed': '#15803D',
  'color.background.accent.green.subtle': '#15803D',
  'color.background.accent.green.subtle.hovered': '#16A34A',
  'color.background.accent.green.subtle.pressed': '#22C55E',
  'color.background.accent.green.bolder': '#4ADE80',
  'color.background.accent.green.bolder.hovered': '#86EFAC',
  'color.background.accent.green.bolder.pressed': '#BBF7D0',

  /* ── Accent: Teal ── */
  'color.background.accent.teal.subtlest': '#042F2E',
  'color.background.accent.teal.subtlest.hovered': '#134E4A',
  'color.background.accent.teal.subtlest.pressed': '#0F766E',
  'color.background.accent.teal.subtler': '#134E4A',
  'color.background.accent.teal.subtler.hovered': '#0F766E',
  'color.background.accent.teal.subtler.pressed': '#0D9488',
  'color.background.accent.teal.subtle': '#0D9488',
  'color.background.accent.teal.subtle.hovered': '#14B8A6',
  'color.background.accent.teal.subtle.pressed': '#2DD4BF',
  'color.background.accent.teal.bolder': '#5EEAD4',
  'color.background.accent.teal.bolder.hovered': '#99F6E4',
  'color.background.accent.teal.bolder.pressed': '#CCFBF1',

  /* ── Accent: Blue ── */
  'color.background.accent.blue.subtlest': '#082F49',
  'color.background.accent.blue.subtlest.hovered': '#0C4A6E',
  'color.background.accent.blue.subtlest.pressed': '#0369A1',
  'color.background.accent.blue.subtler': '#0C4A6E',
  'color.background.accent.blue.subtler.hovered': '#0369A1',
  'color.background.accent.blue.subtler.pressed': '#0284C7',
  'color.background.accent.blue.subtle': '#0284C7',
  'color.background.accent.blue.subtle.hovered': '#0EA5E9',
  'color.background.accent.blue.subtle.pressed': '#38BDF8',
  'color.background.accent.blue.bolder': '#7DD3FC',
  'color.background.accent.blue.bolder.hovered': '#BAE6FD',
  'color.background.accent.blue.bolder.pressed': '#E0F2FE',

  /* ── Accent: Purple ── */
  'color.background.accent.purple.subtlest': '#2E1065',
  'color.background.accent.purple.subtlest.hovered': '#4C1D95',
  'color.background.accent.purple.subtlest.pressed': '#5B21B6',
  'color.background.accent.purple.subtler': '#4C1D95',
  'color.background.accent.purple.subtler.hovered': '#5B21B6',
  'color.background.accent.purple.subtler.pressed': '#6D28D9',
  'color.background.accent.purple.subtle': '#6D28D9',
  'color.background.accent.purple.subtle.hovered': '#7C3AED',
  'color.background.accent.purple.subtle.pressed': '#8B5CF6',
  'color.background.accent.purple.bolder': '#C4B5FD',
  'color.background.accent.purple.bolder.hovered': '#DDD6FE',
  'color.background.accent.purple.bolder.pressed': '#EDE9FE',

  /* ── Accent: Magenta ── */
  'color.background.accent.magenta.subtlest': '#500724',
  'color.background.accent.magenta.subtlest.hovered': '#831843',
  'color.background.accent.magenta.subtlest.pressed': '#9D174D',
  'color.background.accent.magenta.subtler': '#831843',
  'color.background.accent.magenta.subtler.hovered': '#9D174D',
  'color.background.accent.magenta.subtler.pressed': '#BE185D',
  'color.background.accent.magenta.subtle': '#BE185D',
  'color.background.accent.magenta.subtle.hovered': '#DB2777',
  'color.background.accent.magenta.subtle.pressed': '#EC4899',
  'color.background.accent.magenta.bolder': '#F9A8D4',
  'color.background.accent.magenta.bolder.hovered': '#FBCFE8',
  'color.background.accent.magenta.bolder.pressed': '#FCE7F3',

  /* ── Accent: Gray ── */
  'color.background.accent.gray.subtlest': '#09090B',
  'color.background.accent.gray.subtlest.hovered': '#18181B',
  'color.background.accent.gray.subtlest.pressed': '#27272A',
  'color.background.accent.gray.subtler': '#18181B',
  'color.background.accent.gray.subtler.hovered': '#27272A',
  'color.background.accent.gray.subtler.pressed': '#3F3F46',
  'color.background.accent.gray.subtle': '#3F3F46',
  'color.background.accent.gray.subtle.hovered': '#52525B',
  'color.background.accent.gray.subtle.pressed': '#71717A',
  'color.background.accent.gray.bolder': '#A1A1AA',
  'color.background.accent.gray.bolder.hovered': '#D4D4D8',
  'color.background.accent.gray.bolder.pressed': '#E4E4E7',

  /* ── Neutral / Base ── */
  'color.background.disabled': '#18181B',
  'color.background.input': '#09090B',
  'color.background.input.hovered': '#18181B',
  'color.background.input.pressed': '#27272A',
  'color.background.inverse.subtle': 'rgba(255, 255, 255, 0.08)',
  'color.background.inverse.subtle.hovered': 'rgba(255, 255, 255, 0.12)',
  'color.background.inverse.subtle.pressed': 'rgba(255, 255, 255, 0.16)',

  'color.background.neutral': '#18181B',
  'color.background.neutral.hovered': '#27272A',
  'color.background.neutral.pressed': '#3F3F46',
  'color.background.neutral.subtle': '#00000000',
  'color.background.neutral.subtle.hovered': '#18181B',
  'color.background.neutral.subtle.pressed': '#27272A',
  'color.background.neutral.bold': '#18181B',
  'color.background.neutral.bold.hovered': '#27272A',
  'color.background.neutral.bold.pressed': '#3F3F46',

  /* ── Selected ── */
  'color.background.selected': '#1A1A1A',
  'color.background.selected.hovered': '#252525',
  'color.background.selected.pressed': '#2E2E2E',
  'color.background.selected.bold': '#D4D4D4',
  'color.background.selected.bold.hovered': '#E5E5E5',
  'color.background.selected.bold.pressed': '#FAFAFA',

  /* ── Brand ── */
  'color.background.brand.subtlest': '#1A1A1A',
  'color.background.brand.subtlest.hovered': '#252525',
  'color.background.brand.subtlest.pressed': '#2E2E2E',
  'color.background.brand.bold': '#D4D4D4',
  'color.background.brand.bold.hovered': '#E5E5E5',
  'color.background.brand.bold.pressed': '#FAFAFA',
  'color.background.brand.boldest': '#2E2E2E',
  'color.background.brand.boldest.hovered': '#3F3F46',
  'color.background.brand.boldest.pressed': '#52525B',

  /* ── Danger ── */
  'color.background.danger': '#450A0A',
  'color.background.danger.hovered': '#7F1D1D',
  'color.background.danger.pressed': '#991B1B',
  'color.background.danger.subtler': '#7F1D1D',
  'color.background.danger.subtler.hovered': '#991B1B',
  'color.background.danger.subtler.pressed': '#B91C1C',
  'color.background.danger.subtle': '#991B1B',
  'color.background.danger.bold': '#EF4444',
  'color.background.danger.bold.hovered': '#DC2626',
  'color.background.danger.bold.pressed': '#B91C1C',

  /* ── Warning ── */
  'color.background.warning': '#78350F',
  'color.background.warning.hovered': '#92400E',
  'color.background.warning.pressed': '#B45309',
  'color.background.warning.subtler': '#92400E',
  'color.background.warning.subtler.hovered': '#B45309',
  'color.background.warning.subtler.pressed': '#D97706',
  'color.background.warning.subtle': '#92400E',
  'color.background.warning.bold': '#F59E0B',
  'color.background.warning.bold.hovered': '#D97706',
  'color.background.warning.bold.pressed': '#B45309',

  /* ── Success ── */
  'color.background.success': '#052E16',
  'color.background.success.hovered': '#14532D',
  'color.background.success.pressed': '#166534',
  'color.background.success.subtler': '#14532D',
  'color.background.success.subtler.hovered': '#166534',
  'color.background.success.subtler.pressed': '#15803D',
  'color.background.success.subtle': '#14532D',
  'color.background.success.bold': '#22C55E',
  'color.background.success.bold.hovered': '#16A34A',
  'color.background.success.bold.pressed': '#15803D',

  /* ── Discovery ── */
  'color.background.discovery': '#2E1065',
  'color.background.discovery.hovered': '#4C1D95',
  'color.background.discovery.pressed': '#5B21B6',
  'color.background.discovery.subtler': '#4C1D95',
  'color.background.discovery.subtler.hovered': '#5B21B6',
  'color.background.discovery.subtler.pressed': '#6D28D9',
  'color.background.discovery.subtle': '#5B21B6',
  'color.background.discovery.bold': '#8B5CF6',
  'color.background.discovery.bold.hovered': '#7C3AED',
  'color.background.discovery.bold.pressed': '#6D28D9',

  /* ── Information ── */
  'color.background.information': '#172554',
  'color.background.information.hovered': '#1E3A8A',
  'color.background.information.pressed': '#1D4ED8',
  'color.background.information.subtler': '#1E3A8A',
  'color.background.information.subtler.hovered': '#1D4ED8',
  'color.background.information.subtler.pressed': '#2563EB',
  'color.background.information.subtle': '#1D4ED8',
  'color.background.information.bold': '#93C5FD',
  'color.background.information.bold.hovered': '#BFDBFE',
  'color.background.information.bold.pressed': '#DBEAFE'
} as const
